In [3]:
import numpy as np

# Función para realizar el cambio de renglones
def cambiar_renglones(matriz, i, j):
    matriz[[i, j]] = matriz[[j, i]]
    return matriz

# Ingreso de la matriz 3x3
matriz = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
#matriz = np.zeros((3, 3))  # Crear una matriz 3x3 de ceros
"""for i in range(3):
    for j in range(3):
        matriz[i][j] = float(input(f"Ingrese el elemento en la fila {i+1} y la columna {j+1}: "))
"""
print("La matriz original es:")
print(matriz)

# Preguntar al usuario qué renglones desea cambiar
renglon1 = int(input("Ingrese el número del primer renglón a intercambiar (1, 2 o 3): "))
renglon2 = int(input("Ingrese el número del segundo renglón a intercambiar (1, 2 o 3): "))

# Realizar el cambio de renglones
nueva_matriz = cambiar_renglones(matriz, renglon1 - 1, renglon2 - 1)
print(f"La matriz con el cambio de renglones entre el renglón {renglon1} y el renglón {renglon2} es:")
print(nueva_matriz)
def multiplicar_renglon_por_constante(matriz, renglon, constante):
    matriz[renglon - 1] *= constante
    return matriz
renglon = int(input("Ingrese el número del renglón a multiplicar (1, 2 o 3): "))
constante = float(input("Ingrese la constante por la que se multiplicará el renglón: "))

# Realizar la multiplicación del renglón por la constante
nueva_matriz = multiplicar_renglon_por_constante(matriz, renglon, constante)
print(f"La matriz con el renglón {renglon} multiplicado por la constante {constante} es:")
print(nueva_matriz)
def sumar_multiplo_de_renglon(matriz, origen, destino, constante):
    matriz[destino - 1] += constante * matriz[origen - 1]
    return matriz
renglon_origen = int(input("Ingrese el número del renglón a multiplicar(1, 2 o 3): "))
constante_sumar = float(input("Ingrese la constante por la que se multiplicará el renglón escogido: "))
renglon_destino = int(input("Ingrese el número del renglón al que se sumará el resultado del reglon anterior (1, 2 o 3): "))


# Realizar la suma del múltiplo del renglón al otro renglón
matriz = sumar_multiplo_de_renglon(matriz, renglon_origen, renglon_destino, constante_sumar)
print(f"La matriz con el resultado de sumar {constante_sumar} veces el renglón {renglon_origen} al renglón {renglon_destino} es:")
print(matriz)

La matriz original es:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Ingrese el número del primer renglón a intercambiar (1, 2 o 3): 1
Ingrese el número del segundo renglón a intercambiar (1, 2 o 3): 2
La matriz con el cambio de renglones entre el renglón 1 y el renglón 2 es:
[[4. 5. 6.]
 [1. 2. 3.]
 [7. 8. 9.]]
Ingrese el número del renglón a multiplicar (1, 2 o 3): 2
Ingrese la constante por la que se multiplicará el renglón: 2
La matriz con el renglón 2 multiplicado por la constante 2.0 es:
[[4. 5. 6.]
 [2. 4. 6.]
 [7. 8. 9.]]
Ingrese el número del renglón a sumar (1, 2 o 3): 1
Ingrese el número del renglón al que se sumará el resultado (1, 2 o 3): 3
Ingrese la constante por la que se multiplicará el renglón a sumar: 3
La matriz con el resultado de sumar 3.0 veces el renglón 1 al renglón 3 es:
[[ 4.  5.  6.]
 [ 2.  4.  6.]
 [19. 23. 27.]]
